version: '3.8'

services:
  api-node-1:
    image: link-shortener-devops
    volumes:
      - ./data/:/app/data/
    ports:
      - "7001:8080"
    environment:
      - LINKS_PATH=./data/links.json
    
  echo-node:
    image: link-shortener-devops
    depends_on:
      - api-node-1
    volumes:
      - ./data/:/app/data/
    ports:
      - "7002:8080"
    environment:
      - LINKS_PATH=./data/links.json
    command: ["echo", "API container is up!"]